### ISSUE TITLE
Error TS2403: 

### ISSUE THREAD

**Issue by rollsroyc3** [react-native-community/bob#18]
My builds just recently started failling, and from what I can see its after React-Native-Image-Picker calls bob build.. Curious if anyone has seen this issue or has any suggestions..

```
npm ERR! prepareGitDep > react-native-image-picker@1.1.0 prepare /Users/andrewroyce/.npm/_cacache/tmp/git-clone-5c2ee5f6
npm ERR! prepareGitDep > bob build
npm ERR! prepareGitDep 
npm ERR! prepareGitDep ℹ Building target commonjs
npm ERR! prepareGitDep ℹ Cleaning up previous build at lib/commonjs
npm ERR! prepareGitDep ℹ Compiling 4 files in src with babel
npm ERR! prepareGitDep ✓ Wrote files to lib/commonjs
npm ERR! prepareGitDep ℹ Building target module
npm ERR! prepareGitDep ℹ Cleaning up previous build at lib/module
npm ERR! prepareGitDep ℹ Compiling 4 files in src with babel
npm ERR! prepareGitDep ✓ Wrote files to lib/module
npm ERR! prepareGitDep ℹ Building target typescript
npm ERR! prepareGitDep ℹ Cleaning up previous build at lib/typescript
npm ERR! prepareGitDep ℹ Generating type definitions with tsc
npm ERR! prepareGitDep ✖ Errors found when building definition files:
npm ERR! prepareGitDep node_modules/@types/react-native/index.d.ts:9391:9 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'Require', but here has type 'NodeRequire'.
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 9391     var require: NodeRequire;
npm ERR! prepareGitDep              ~~~~~~~
npm ERR! prepareGitDep 
npm ERR! prepareGitDep   node_modules/@types/node/globals.d.ts:167:13
npm ERR! prepareGitDep     167 declare var require: NodeJS.Require;
npm ERR! prepareGitDep                     ~~~~~~~
npm ERR! prepareGitDep     'require' was also declared here.
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 
npm ERR! prepareGitDep Found 1 error.
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm ERR! prepareGitDep npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm ERR! prepareGitDep npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm ERR! prepareGitDep npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm ERR! prepareGitDep clang: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX' [-Wincompatible-sysroot]
npm ERR! prepareGitDep clang: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX' [-Wincompatible-sysroot]
npm ERR! prepareGitDep In file included from ../fsevents.cc:72:
npm ERR! prepareGitDep ../src/thread.cc:36:25: error: unknown type name 'ConstFSEventStreamRef'
npm ERR! prepareGitDep void HandleStreamEvents(ConstFSEventStreamRef stream, void *ctx, size_t numEvents, void *eventPaths, const FSEventStreamEventFlags eventFlags[], const FSEventStreamEventId eventIds[]) {
npm ERR! prepareGitDep                         ^
npm ERR! prepareGitDep ../src/thread.cc:36:108: error: unknown type name 'FSEventStreamEventFlags'
npm ERR! prepareGitDep void HandleStreamEvents(ConstFSEventStreamRef stream, void *ctx, size_t numEvents, void *eventPaths, const FSEventStreamEventFlags eventFlags[], const FSEventStreamEventId eventIds[]) {
npm ERR! prepareGitDep                                                                                                            ^
npm ERR! prepareGitDep ../src/thread.cc:36:152: error: unknown type name 'FSEventStreamEventId'
npm ERR! prepareGitDep void HandleStreamEvents(ConstFSEventStreamRef stream, void *ctx, size_t numEvents, void *eventPaths, const FSEventStreamEventFlags eventFlags[], const FSEventStreamEventId eventIds[]) {
npm ERR! prepareGitDep                                                                                                                                                        ^
npm ERR! prepareGitDep ../src/thread.cc:54:3: error: unknown type name 'FSEventStreamContext'
npm ERR! prepareGitDep   FSEventStreamContext context = { 0, ctx, NULL, NULL, NULL };
npm ERR! prepareGitDep   ^
npm ERR! prepareGitDep ../src/thread.cc:56:3: error: unknown type name 'FSEventStreamRef'
npm ERR! prepareGitDep   FSEventStreamRef stream = FSEventStreamCreate(NULL, &HandleStreamEvents, &context, fse->paths, kFSEventStreamEventIdSinceNow, (CFAbsoluteTime) 0.1, kFSEventStreamCreateFlagNone | kFSEventStreamCreateFlagWatchRoot | kFSEventStreamCreateFlagFileEvents | kFSEventStreamCreateFlagUseCFTypes);
npm ERR! prepareGitDep   ^
npm ERR! prepareGitDep ../src/thread.cc:56:98: error: use of undeclared identifier 'kFSEventStreamEventIdSinceNow'
npm ERR! prepareGitDep   FSEventStreamRef stream = FSEventStreamCreate(NULL, &HandleStreamEvents, &context, fse->paths, kFSEventStreamEventIdSinceNow, (CFAbsoluteTime) 0.1, kFSEventStreamCreateFlagNone | kFSEventStreamCreateFlagWatchRoot | kFSEventStreamCreateFlagFileEvents | kFSEventStreamCreateFlagUseCFTypes);
npm ERR! prepareGitDep                                                                                                  ^
npm ERR! prepareGitDep 6 errors generated.
npm ERR! prepareGitDep make: *** [Release/obj.target/fse/fsevents.o] Error 1
npm ERR! prepareGitDep gyp ERR! build error 
npm ERR! prepareGitDep gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! prepareGitDep gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
npm ERR! prepareGitDep gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
npm ERR! prepareGitDep gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
npm ERR! prepareGitDep gyp ERR! System Darwin 17.7.0
npm ERR! prepareGitDep gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! prepareGitDep gyp ERR! cwd /Users/andrewroyce/.npm/_cacache/tmp/git-clone-5c2ee5f6/node_modules/fsevents
npm ERR! prepareGitDep gyp ERR! node -v v10.15.3
npm ERR! prepareGitDep gyp ERR! node-gyp -v v3.8.0
npm ERR! prepareGitDep gyp ERR! not ok 
npm ERR! prepareGitDep bob build
npm ERR! prepareGitDep 
npm ERR! prepareGitDep build files for publishing
npm ERR! prepareGitDep 
npm ERR! prepareGitDep Options:
npm ERR! prepareGitDep   --help     Show help                                                 [boolean]
npm ERR! prepareGitDep   --version  Show version number                                       [boolean]
npm ERR! prepareGitDep 
npm ERR! prepareGitDep Error: Failed to build definition files.
npm ERR! prepareGitDep     at build (/Users/andrewroyce/.npm/_cacache/tmp/git-clone-5c2ee5f6/node_modules/@react-native-community/bob/lib/targets/typescript.js:77:11)
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! react-native-image-picker@1.1.0 prepare: `bob build`
npm ERR! prepareGitDep npm ERR! Exit status 1
npm ERR! prepareGitDep npm ERR! 
npm ERR! prepareGitDep npm ERR! Failed at the react-native-image-picker@1.1.0 prepare script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     /Users/andrewroyce/.npm/_logs/2019-12-23T22_03_41_453Z-debug.log
npm ERR! prepareGitDep 
```

**Comment by Santhosh-candid** [comment]
@rollsroyc3  Seeing same issue ^^ Any luck ?

**Comment by rollsroyc3** [comment]
Yeah, sorry actually posted it in the react-native-image-picker repo..

https://github.com/react-native-community/react-native-image-picker/issues/1254

**Comment by satya164** [comment]
Bob just uses your own typescript config. Make sure that you don't have any TypeScript errors when generating definitions with the `--declaration` flag.

**Comment by rollsroyc3** [comment]
Hmm I don't use typescript in my project and like I said before, nothing changed in my project between this build and the last.. It just started failing on bitrise, I assumed it was one of my package.json dependencies using the ^ that might have caused the issue.

**Comment by Santhosh-candid** [comment]
@satya164  thanks will check your suggestion. Similar to @rollsroyc3 nothing changed in our repo and builds(both local and CI) started failing around Dec23rd

**Comment by satya164** [comment]
> Hmm I don't use typescript in my project and like I said before, nothing changed in my project between this build and the last

Well you are installing react-native-image-picker from git which uses typescript. If there is an issue with image picker, they'll need to fix it.

> nothing changed in our repo and builds(both local and CI) started failing around Dec23rd

If you're not using a lockfile, then you should. And when installing deps from git, always point to a SHA instead of installing from master. Anyway, this is unrelated to bob. If there are TS issues in image picker repo, it needs to be fixed there.
