### ISSUE TITLE
✖ Errors found when building definition files. error TS5023: Unknown compiler option 'emitdeclarationonly'.

### ISSUE THREAD

**Issue by gaodeng** [react-native-community/bob#2]
```
> bob build

ℹ Building target commonjs
ℹ Cleaning up previous build
ℹ Compiling 7 files in src with babel
✓ Wrote files to lib/commonjs
ℹ Building target module
ℹ Cleaning up previous build
ℹ Compiling 7 files in src with babel
✓ Wrote files to lib/module
ℹ Building target typescript
ℹ Cleaning up previous build
ℹ Generating type definitions with tsc
✖ Errors found when building definition files.
error TS5023: Unknown compiler option 'emitdeclarationonly'.

bob build

build files for publishing

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]

Error: Failed to build definition files.
    at build (/Users/gaodeng/Documents/work/moonfmlib/node_modules/@react-native-community/bob/lib/targets/typescript.js:46:11)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! moonfmlib@1.0.0 prepare: `bob build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the moonfmlib@1.0.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gaodeng/.npm/_logs/2019-04-20T00_22_55_222Z-debug.log
```

**Comment by satya164** [comment]
What version of typescript are you using? Can you share a link to the library?

**Comment by gaodeng** [comment]
my bad.I used an old version typescipt.

**Comment by SaeedZhiany** [comment]
In react-native-svg we are using `"typescript": "^3.7.1-rc"` and still getting this error. What should we do @satya164?

```
Error: Failed to build definition files.
    at build (PATH_TO_LIB\react-native-svg\node_modules\@react-native-community\bob\lib\targets\typescript.js:82:11)
    at async Object.handler (PATH_TO_LIB\react-native-svg\node_modules\@react-native-community\bob\lib\cli.js:299:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-native-svg@9.13.5 bob: `bob build`
npm ERR! Exit status 1
```

**Comment by satya164** [comment]
Can you post the full error?

**Comment by SaeedZhiany** [comment]
here is the stack trace I'm getting:

```
PS PATH_TO_LIB\react-native-svg> npm run bob

> react-native-svg@9.13.5 bob PATH_TO_LIB\react-native-svg
> bob build

ℹ Building target commonjs
ℹ Cleaning up previous build at lib\commonjs
ℹ Compiling 53 files in src with babel
✓ Wrote files to lib\commonjs
ℹ Building target module
ℹ Cleaning up previous build at lib\module
ℹ Compiling 53 files in src with babel
✓ Wrote files to lib\module
ℹ Building target typescript
ℹ Cleaning up previous build at lib\typescript
ℹ Generating type definitions with tsc
'C:\Users\USER\Desktop\New' is not recognized as an internal or external command,
operable program or batch file.
✖ Errors found when building definition files:

bob.js build

build files for publishing

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]

Error: Failed to build definition files.
    at build (PATH_TO_LIB\react-native-svg\node_modules\@react-native-community\bob\lib\targets\typescript.js:82:11)
    at async Object.handler (PATH_TO_LIB\react-native-svg\node_modules\@react-native-community\bob\lib\cli.js:299:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-native-svg@9.13.5 bob: `bob build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-native-svg@9.13.5 bob script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USER\AppData\Roaming\npm-cache\_logs\2019-12-10T14_18_14_970Z-debug.log
```

**Comment by satya164** [comment]
Your error is related to path containing spaces and different from this. Can you open a new issue about it?

**Comment by SaeedZhiany** [comment]
Oh, you're right. so I can fix my path as a workaround, right?

Ok, I open another issue for that, Thanks.

**Comment by SaeedZhiany** [comment]
@satya164 
I create [the issue](https://github.com/react-native-community/bob/issues/12)

**Comment by cengit** [comment]
i was getting same error, but a little bit difference.

root cause for me is: **there is lower typescript version dependency in the third party libs.**

I Created an issue in my github to document the entire fixing process:

https://github.com/cengit/react-native-issue/issues/3

**Comment by stackchain** [comment]
hey folks, facing a similar issue here: `https://github.com/Emurgo/yoroi/actions/runs/5743175494/job/15566875111#step:4:130`
it doesn't look to be related to space in path, yet maybe it related to workspace?

**Comment by satya164** [comment]
@stackchain from the error message it looks like it's using an old version of TypeScript. I'd suggest checking that you have a recent version of TypeScript across your monorepo. It's also best to use a single version of TS for all packages in the monorepo.
